import json
import os
import re
from pathlib import Path

# ================= 配置项 =================
# JSON源文件所在目录
RAW_DIR = Path('/Users/1k/code/YiBao/jyk/基础参数类型/JSON') 
# 生成的目标Python文件
OUTPUT_FILE = 'const_mappings.py'
# =========================================

def generate_code():
    # 1. 准备文件头部
    lines = [
        "# -*- coding: utf-8 -*-",
        "# This file is auto-generated by generate_mappings.py",
        "# DO NOT EDIT MANUALLY unless you want to add custom aliases.",
        "",
        "class Mappings:",
    ]
    
    router_map = {} # 用于存储 { "OCR字段名": "Mappings类变量名" }

    # 2. 遍历目录
    if not RAW_DIR.exists():
        print(f"Error: 目录 {RAW_DIR} 不存在")
        return

    json_files = sorted(list(RAW_DIR.glob('*.json')))
    print(f"找到 {len(json_files)} 个配置文件，开始处理...")

    for file_path in json_files:
        filename = file_path.stem # e.g., "1_运输方式_1009"
        
        # --- 核心逻辑：从文件名解析信息 ---
        # 正则匹配：数字_中文名称_数字
        match = re.match(r'(\d+)_(.+?)_(\d+)', filename)
        
        if match:
            # seq = match.group(1)      # 序号 (如 1)
            field_name = match.group(2) # 字段名 (如 "运输方式") - 将作为路由的Key
            code_id = match.group(3)    # 代码 (如 "1009")
            
            # 生成唯一的变量名，例如: DICT_1009_运输方式
            var_name = f"DICT_{code_id}_{field_name}"
        else:
            print(f"警告: 文件名格式不符合 '序号_名称_代码.json' 规范: {filename}")
            # 降级处理：直接用文件名作为变量名，不加入自动路由
            var_name = f"DICT_{filename.replace(' ', '_')}"
            field_name = None

        try:
            with open(file_path, 'r', encoding='utf-8') as f:
                data = json.load(f)
            
            # --- 提取映射字典 ---
            result_list = data.get('message', {}).get('resultList', [])
            mapping_dict = {}
            for item in result_list:
                # 提取 paramValue (中文) 和 paramKey (代码)
                if 'paramValue' in item and 'paramKey' in item:
                    # key使用 strip() 去除空格，保证匹配率
                    k = item['paramValue'].strip()
                    v = item['paramKey'].strip()
                    mapping_dict[k] = v
            
            # --- 写入 Mappings 类代码 ---
            # dump时 ensure_ascii=False 保证生成的py文件里是中文，方便调试
            dict_str = json.dumps(mapping_dict, ensure_ascii=False, indent=4)
            lines.append(f"    # Source: {filename}.json")
            lines.append(f"    {var_name} = {dict_str}")
            lines.append("") # 空行

            # 记录到路由表
            if field_name:
                router_map[field_name] = f"Mappings.{var_name}"
                
            print(f"✔ 已处理: {field_name} (Code: {code_id}) -> {len(mapping_dict)} 条目")

        except Exception as e:
            print(f"❌ 处理失败 {filename}: {e}")

    # 3. 生成 Router 类
    lines.append("class FieldRouter:")
    lines.append("    # 字段名 -> 字典数据的路由表")
    lines.append("    MAP = {")
    
    for key, val_ref in router_map.items():
        lines.append(f"        '{key}': {val_ref},")
        
    lines.append("    }")

    # 4. 写入最终文件
    with open(OUTPUT_FILE, 'w', encoding='utf-8') as f_out:
        f_out.write("\n".join(lines))
    
    print(f"\n生成完毕! 文件路径: {OUTPUT_FILE}")

if __name__ == '__main__':
    generate_code()